### ISSUE TITLE
Error installing netdata

### ISSUE THREAD

**Issue by alexborisov** [j8r/DPlatform#6]
The installer seems to successfully install netdata, but upon completion I'm unable to access it via the URL. It doesn't show up in running processes and I cannot find a launchable service for it. It did create a folder `/root/netdata` which seems to be the install path....

**Comment by j8r** [comment]
Thank you for the report! If netdata runs, it will be only in local. A reverse proxy, or maybe just modifying a configuration file is needed. I've also noticed some changes in netdata since this script was made, the installation may be not successful. I will do a rework this next days.

**Comment by j8r** [comment]
@alexborisov The netdata installation should be fixed now, with a nginx reverse proxy.

**Comment by alexborisov** [comment]
@j8r thanks for the update. I've just tried with the latest version, but i still cannot connect. Do I need to configure something? Regarding your comment about being local, do you mean i cannot access it via another computer on the network? My pi is headless. I'm trying on port 19999 as per the instructions, but I'm getting a `refused to connect` error. Dropping the port I get the default nginx landing page so thats working.

**Comment by alexborisov** [comment]
I ran `sudo ~/DPlatform-ShellCore/netdata/netdata-installer.sh` manually and now it works.

**Comment by j8r** [comment]
I've missed to add  `cd` to have the git repo cloned to `/root` and not in `~/DPlatform-ShellCore`, and to have the followed command `~/netdata/netdata-installer.sh` executed next.
Fixed now, thanks for your feedback!
